In [1]:
import folium
import geopandas as gpd
import pandas as pd
import branca
import branca.colormap as cm
import py7zr
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)

ModuleNotFoundError: No module named 'folium'

### County Boundaries for US

In [4]:
#bring in county boundaries
url = 'https://www2.census.gov/geo/tiger/TIGER2020/COUNTY/tl_2020_us_county.zip'
counties = gpd.read_file(url)
counties = counties.to_crs(2274)
print('Your geographic file is ready.')

Your geographic file is ready.

In [5]:
counties.head(2)

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,31,039,00835841,31039,Cuming,Cuming County,06,H1,G4020,NaN,NaN,NaN,A,1477645345,10690204,+41.9158651,-096.7885168,"POLYGON ((-1037974.364 2967266.342, -1037940.7..."
1,53,069,01513275,53069,Wahkiakum,Wahkiakum County,06,H1,G4020,NaN,NaN,NaN,A,680976231,61568965,+46.2946377,-123.4244583,"POLYGON ((-7436609.083 6179626.086, -7437671.8..."

### Census Tract Boundaries for US

In [6]:
#bring in Census Tract boundaries
url = 'https://www2.census.gov/geo/tiger/TIGER2020/TRACT/tl_2020_47_tract.zip'
tract = gpd.read_file(url)
tract = tract.to_crs(2274)
print('Your geographic file is ready.')

Your geographic file is ready.

In [7]:
tract.head(2)

,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,47,175,925200,47175925200,9252,Census Tract 9252,G5020,S,227429512,1667739,+35.7438100,-085.4940227,"POLYGON ((2082675.432 519925.582, 2082697.390 ..."
1,47,175,925000,47175925000,9250,Census Tract 9250,G5020,S,480712883,1225717,+35.6695378,-085.4220628,"POLYGON ((2085729.499 500819.396, 2085736.575 ..."

### Read in Compressed Drive-Time Laborshed

In [6]:
file_path = 'data/Travel_Bands_45min_to_Tower.7z'
extract_dir = 'data/extracted/powercomlaborshed.shp'

In [7]:
with py7zr.SevenZipFile(file_path, mode='r') as z:
    z.extractall(path=extract_dir)

In [8]:
shp_filename = [filename for filename in os.listdir(extract_dir) if filename.endswith(".shp")][0]
shp_path = os.path.join(extract_dir, shp_filename)

In [9]:
gdf = gpd.read_file(shp_path)

In [10]:
gdf.head()

   ID         AREA  FROM    TO                                           geometry
0   1  1287.844849   0.0  45.0  POLYGON ((1787153.127 667148.891, 1787157.307 ...

## Clip DataFrames to Each Other

In [17]:
gdf1 = zcta.sjoin(counties, how = 'left')
gdf1 = gdf1[['STATEFP_left', 'COUNTYFP_left', 'GEOID_left', 'NAME_left', 'TRACTCE', 'geometry']]
gdf1.head()

  STATEFP_left COUNTYFP_left   GEOID_left NAME_left TRACTCE                                           geometry
0           47           175  47175925200      9252  925200  POLYGON ((2082675.432 519925.582, 2082697.390 ...
0           47           175  47175925200      9252  925200  POLYGON ((2082675.432 519925.582, 2082697.390 ...
0           47           175  47175925200      9252  925200  POLYGON ((2082675.432 519925.582, 2082697.390 ...
1           47           175  47175925000      9250  925000  POLYGON ((2085729.499 500819.396, 2085736.575 ...
1           47           175  47175925000      9250  925000  POLYGON ((2085729.499 500819.396, 2085736.575 ...

In [12]:
gdf1.head()

,STATEFP_left,COUNTYFP_left,TRACTCE,GEOID_left,NAME_left,NAMELSAD_left,MTFCC_left,FUNCSTAT_left,ALAND_left,AWATER_left,INTPTLAT_left,INTPTLON_left,geometry,index_right,STATEFP_right,COUNTYFP_right,COUNTYNS,GEOID_right,NAME_right,NAMELSAD_right,LSAD,CLASSFP,MTFCC_right,CSAFP,CBSAFP,METDIVFP,FUNCSTAT_right,ALAND_right,AWATER_right,INTPTLAT_right,INTPTLON_right
0,47,175,925200,47175925200,9252,Census Tract 9252,G5020,S,227429512,1667739,+35.7438100,-085.4940227,"POLYGON ((2082675.432 519925.582, 2082697.390 ...",563,47,177,01639796,47177,Warren,Warren County,06,H1,G4020,NaN,32660,NaN,A,1120619165,3524883,+35.6782498,-085.7773428
0,47,175,925200,47175925200,9252,Census Tract 9252,G5020,S,227429512,1667739,+35.7438100,-085.4940227,"POLYGON ((2082675.432 519925.582, 2082697.390 ...",1226,47,175,01648584,47175,Van Buren,Van Buren County,06,H1,G4020,NaN,NaN,NaN,A,708142395,2893456,+35.6992335,-085.4584092
0,47,175,925200,47175925200,9252,Census Tract 9252,G5020,S,227429512,1667739,+35.7438100,-085.4940227,"POLYGON ((2082675.432 519925.582, 2082697.390 ...",67,47,185,01639800,47185,White,White County,06,H1,G4020,NaN,NaN,NaN,A,975592109,7113368,+35.9270486,-085.4557854
1,47,175,925000,47175925000,9250,Census Tract 9250,G5020,S,480712883,1225717,+35.6695378,-085.4220628,"POLYGON ((2085729.499 500819.396, 2085736.575 ...",1309,47,153,01652643,47153,Sequatchie,Sequatchie County,06,H1,G4020,174,16860,NaN,A,688550848,498315,+35.3723358,-085.4100820
1,47,175,925000,47175925000,9250,Census Tract 9250,G5020,S,480712883,1225717,+35.6695378,-085.4220628,"POLYGON ((2085729.499 500819.396, 2085736.575 ...",2425,47,007,01639725,47007,Bledsoe,Bledsoe County,06,H1,G4020,NaN,NaN,NaN,A,1052973468,858669,+35.5935612,-085.2059104

In [18]:
gdf2 = gdf.sjoin(gdf1, how = 'left')
gdf2 = gdf2[['STATEFP_left', 'COUNTYFP_left', 'GEOID_left', 'NAME_left', 'TRACTCE']]
gdf2

  STATEFP_left COUNTYFP_left   GEOID_left NAME_left TRACTCE
0           47           041  47041920101   9201.01  920101
0           47           041  47041920101   9201.01  920101
0           47           189  47189030904    309.04  030904
0           47           189  47189030904    309.04  030904
0           47           189  47189031000       310  031000
0           47           189  47189031000       310  031000
0           47           189  47189031000       310  031000
0           47           189  47189031000       310  031000
0           47           189  47189031000       310  031000
0           47           189  47189030800       308  030800
0           47           189  47189030402    304.02  030402
0           47           041  47041920101   9201.01  920101
0           47           041  47041920300      9203  920300
0           47           041  47041920300      9203  920300
0           47           041  47041920300      9203  920300
0           47           041  47041920300      9203  920300
0           47           041  47041920300      9203  920300
0           47           141  47141001100        11  001100
0           47           141  47141001100        11  001100
0           47           141  47141001100        11  001100
0           47           159  47159975400      9754  975400
0           47           159  47159975400      9754  975400
0           47           159  47159975400      9754  975400
0           47           159  47159975400      9754  975400
0           47           141  47141001000        10  001000
0           47           141  47141001000        10  001000
0           47           141  47141001000        10  001000
0           47           141  47141001000        10  001000
0           47           159  47159975300      9753  975300
0           47           159  47159975300      9753  975300
0           47           159  47159975300      9753  975300
0           47           149  47149041000       410  041000
0           47           149  47149040501    405.01  040501
0           47           149  47149040501    405.01  040501
0           47           149  47149040501    405.01  040501
0           47           189  47189030700       307  030700
0           47           189  47189030600       306  030600
0           47           189  47189030401    304.01  030401
0           47           189  47189030202    302.02  030202
0           47           189  47189030500       305  030500
0           47           189  47189030105    301.05  030105
0           47           159  47159975200      9752  975200
0           47           159  47159975200      9752  975200
0           47           159  47159975200      9752  975200
0           47           189  47189030102    301.02  030102
0           47           189  47189030102    301.02  030102
0           47           189  47189030102    301.02  030102
0           47           189  47189030103    301.03  030103
0           47           189  47189030103    301.03  030103
0           47           189  47189030103    301.03  030103
0           47           189  47189030104    301.04  030104
0           47           189  47189030104    301.04  030104
0           47           165  47165020901    209.01  020901
0           47           165  47165020901    209.01  020901
0           47           165  47165020603    206.03  020603
0           47           159  47159975100      9751  975100
0           47           087  47087960200      9602  960200
0           47           087  47087960200      9602  960200
0           47           087  47087960200      9602  960200
0           47           159  47159975000      9750  975000
0           47           159  47159975000      9750  975000
0           47           159  47159975000      9750  975000
0           47           159  47159975000      9750  975000
0           47           087  47087960100      9601  960100
0           47           087  47087960100      9601  960100
0           47           087  47087960100      9601  960100
0           47           087  47087960100      9601  960100
0           47           165  47165020603    206.03  020603
0           47           165  47165020603    206.03  020603
0           47           169  47169090100       901  090100
0           47           169  47169090100       901  090100
0           47           169  47169090100       901  090100
0           47           169  47169090100       901  090100
0           47           169  47169090100       901  090100
0           47           169  47169090200       902  090200
0           47           165  47165020602    206.02  020602
0           47           165  47165020602    206.02  020602
0           47           165  47165020602    206.02  020602
0           47           165  47165020601    206.01  020601
0           47           111  47111970302   9703.02  970302
0           47           111  47111970302   9703.02  970302
0           47           111  47111970302   9703.02  970302
0           47           111  47111970301   9703.01  970301
0           47           111  47111970400      9704  970400
0           47           111  47111970400      9704  970400
0           47           111  47111970400      9704  970400
0           47           111  47111970400      9704  970400
0           47           111  47111970100      9701  970100
0           47           111  47111970100      9701  970100
0           47           111  47111970100      9701  970100
0           47           111  47111970100      9701  970100
0           47           111  47111970100      9701  970100
0           47           165  47165020101    201.01  020101
0           47           165  47165020101    201.01  020101
0           47           111  47111970200      9702  970200
0           47           111  47111970200      9702  970200
0           47           111  47111970200      9702  970200
0           47           165  47165020102    201.02  020102
0           47           165  47165020102    201.02  020102
0           47           165  47165020102    201.02  020102
0           47           165  47165020102    201.02  020102
0           47           037  47037015635    156.35  015635
0           47           037  47037015635    156.35  015635
0           47           037  47037015635    156.35  015635
0           47           189  47189030905    309.05  030905
0           47           189  47189030905    309.05  030905
0           47           189  47189030906    309.06  030906
0           47           189  47189030906    309.06  030906
0           47           189  47189030906    309.06  030906
0           47           037  47037015633    156.33  015633
0           47           037  47037015633    156.33  015633
0           47           189  47189030907    309.07  030907
0           47           037  47037015632    156.32  015632
0           47           189  47189030908    309.08  030908
0           47           037  47037015609    156.09  015609
0           47           189  47189030310    303.10  030310
0           47           189  47189030310    303.10  030310
0           47           037  47037015622    156.22  015622
0           47           037  47037015622    156.22  015622
0           47           037  47037015623    156.23  015623
0           47           189  47189030311    303.11  030311
0           47           189  47189030311    303.11  030311
0           47           189  47189030309    303.09  030309
0           47           189  47189030203    302.03  030203
0           47           189  47189030206    302.06  030206
0           47           189  47189030205    302.05  030205
0           47           189  47189030205    302.05  030205
0           47           189  47189030207    302.07  030207
0           47           189  47189030207    302.07  030207
0           47           165  47165020903    209.03  020903
0           47           165  47165020903    209.03  020903
0           47           165  47165020501    205.01  020501
0           47           165  47165020904    209.04  020904
0           47           165  47165020905    209.05  020905
0           47           165  47165020700       207  020700
0           47           165  47165020800       208  020800
0           47           165  47165020502    205.02  020502
0           47           165  47165020503    205.03  020503

In [75]:
#gdf2.to_csv('zctas.csv', index = False)

In [19]:
gdf2.to_csv('tracts.csv', index = False)

In [20]:
gdf2['TRACTCE'].unique()

array(['920101', '030904', '031000', '030800', '030402', '920300',
       '001100', '975400', '001000', '975300', '041000', '040501',
       '030700', '030600', '030401', '030202', '030500', '030105',
       '975200', '030102', '030103', '030104', '020901', '020603',
       '975100', '960200', '975000', '960100', '090100', '090200',
       '020602', '020601', '970302', '970301', '970400', '970100',
       '020101', '970200', '020102', '015635', '030905', '030906',
       '015633', '030907', '015632', '030908', '015609', '030310',
       '015622', '015623', '030311', '030309', '030203', '030206',
       '030205', '030207', '020903', '020501', '020904', '020905',
       '020700', '020800', '020502', '020503'], dtype=object)